
'use strict';
const express=require('express'),cors=require('cors'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const app=express();app.use(cors());app.use(express.json({limit:'2mb'}));
const PORT=Number(process.env.PORT)||10000,DIR=process.env.MP_DATA_DIR||(fs.existsSync('/var/data')?'/var/data':path.join(__dirname,'data'));fs.mkdirSync(DIR,{recursive:true});
const FILE=path.join(DIR,'mongol-poker-tables.json');let tables=Object.create(null);
try{if(fs.existsSync(FILE))tables=JSON.parse(fs.readFileSync(FILE,'utf8'))||Object.create(null)}catch(e){console.error('Load:',e)}
const id=x=>String(x??'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80),num=x=>Number.isSafeInteger(Number(x))&&Number(x)>=0?Number(x):0;
function save(t){t.revision=(t.revision||0)+1;t.updatedAt=Date.now();const tmp=FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(tables));fs.renameSync(tmp,FILE)}
function error(res,code,status=400,t=null,pid=''){return res.status(status).json({ok:false,code,...(t?{state:view(t,pid)}:{})})}
function cards(){const a=[];for(const s of ['♠','♥','♦','♣'])for(let r=2;r<=14;r++)a.push({s,r});for(let i=a.length-1;i>0;i--){const j=crypto.randomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
const take=t=>t.deck.pop();
const seats=t=>t.players.map((p,i)=>p&&p.chips>0?i:-1).filter(i=>i>=0);
function around(t,from,pred){for(let j=1;j<=t.players.length;j++){const i=(from+j+t.players.length)%t.players.length;if(pred(i))return i}return -1}
const live=(t,i)=>!!t.players[i]&&!t.folded[i];
const canAct=(t,i)=>live(t,i)&&t.players[i].chips>0;
function pay(t,i,amount){const n=Math.min(t.players[i].chips,Math.max(0,Math.floor(amount)));t.players[i].chips-=n;t.liveSeatBets[i]+=n;t.contributions[i]+=n;t.potAmt+=n;return n}
function score5(cs){const rs=cs.map(c=>c.r).sort((a,b)=>b-a),cnt={};for(const r of rs)cnt[r]=(cnt[r]||0)+1;const groups=Object.entries(cnt).map(([r,n])=>[n,+r]).sort((a,b)=>b[0]-a[0]||b[1]-a[1]);const flush=cs.every(c=>c.s===cs[0].s);const u=[...new Set(rs)];if(u.includes(14))u.push(1);let straight=0;for(let i=0;i<=u.length-5;i++)if(u[i]-u[i+4]===4){straight=u[i];break}if(flush&&straight)return[8,straight];if(groups[0][0]===4)return[7,groups[0][1],groups[1][1]];if(groups[0][0]===3&&groups[1][0]>=2)return[6,groups[0][1],groups[1][1]];if(flush)return[5,...rs];if(straight)return[4,straight];if(groups[0][0]===3)return[3,groups[0][1],...groups.slice(1).map(g=>g[1]).sort((a,b)=>b-a)];if(groups[0][0]===2&&groups[1][0]===2)return[2,groups[0][1],groups[1][1],groups[2][1]];if(groups[0][0]===2)return[1,groups[0][1],...groups.slice(1).map(g=>g[1]).sort((a,b)=>b-a)];return[0,...rs]}
function cmp(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]||0)-(b[i]||0);if(d)return d}return 0}
function best(t,i){const h=t.holes[i],b=t.boardCards,all=t.currentTable.type==='omaha'?h:[...h,...b];let top=null;function eval5(cs){const s=score5(cs);if(!top||cmp(s,top)>0)top=s}if(t.currentTable.type==='omaha'){for(let a=0;a<h.length;a++)for(let c=a+1;c<h.length;c++)for(let d=0;d<b.length;d++)for(let e=d+1;e<b.length;e++)for(let f=e+1;f<b.length;f++)eval5([h[a],h[c],b[d],b[e],b[f]])}else{for(let a=0;a<all.length;a++)for(let c=a+1;c<all.length;c++)for(let d=c+1;d<all.length;d++)for(let e=d+1;e<all.length;e++)for(let f=e+1;f<all.length;f++)eval5([all[a],all[c],all[d],all[e],all[f]])}return top||[0]}
function finish(t){const alive=t.players.map((p,i)=>live(t,i)?i:-1).filter(i=>i>=0);if(alive.length>1)while(t.boardCards.length<5){if(t.boardCards.length===0||t.boardCards.length===3||t.boardCards.length===4)take(t);t.boardCards.push(take(t))}const levels=[...new Set(t.contributions.filter(n=>n>0))].sort((a,b)=>a-b);let prev=0,totalRake=0,winners=[];for(const level of levels){const contributors=t.contributions.map((n,i)=>n>=level?i:-1).filter(i=>i>=0);const gross=(level-prev)*contributors.length;prev=level;const eligible=contributors.filter(i=>live(t,i));if(!eligible.length)throw Error('No eligible winner');let chosen=eligible;if(eligible.length>1){let high=null;chosen=[];for(const i of eligible){const s=best(t,i);if(!high||cmp(s,high)>0){high=s;chosen=[i]}else if(cmp(s,high)===0)chosen.push(i)}}const rake=Math.floor(gross*0.02);totalRake+=rake;const prize=gross-rake;chosen.sort((a,b)=>((a-t.liveDealer+t.players.length)%t.players.length)-((b-t.liveDealer+t.players.length)%t.players.length));chosen.forEach((i,k)=>{t.players[i].chips+=Math.floor(prize/chosen.length)+(k<prize%chosen.length?1:0)});winners.push(...chosen)}t.rakeTotal=(t.rakeTotal||0)+totalRake;t.showdownWinners=[...new Set(winners)];t.liveWinner=t.showdownWinners[0]??-1;t.potAmt=0;t.finished=true;t.liveTurn=-1;t.turnDeadline=0;t.nextHandAt=Date.now()+3500;t.statusText='Гар дууслаа'}
function nextStreet(t){const alive=t.players.filter((p,i)=>live(t,i));if(alive.length<=1)return finish(t);if(t.street>=3)return finish(t);t.street++;take(t);for(let j=0;j<(t.street===1?3:1);j++)t.boardCards.push(take(t));t.liveSeatBets=t.players.map(()=>0);t.toCall=0;t.minRaise=num(t.currentTable.bb)||200;t.acted=t.players.map(()=>false);t.liveTurn=around(t,t.liveDealer,i=>canAct(t,i));if(t.liveTurn<0)return runout(t);t.turnDeadline=Date.now()+20000}
function runout(t){while(!t.finished){if(t.street>=3){finish(t);break}nextStreet(t)}}
function settle(t,after){const alive=t.players.map((p,i)=>live(t,i)?i:-1).filter(i=>i>=0);if(alive.length<=1)return finish(t);const actors=alive.filter(i=>canAct(t,i));if(!actors.length)return runout(t);const pending=actors.filter(i=>!t.acted[i]||t.liveSeatBets[i]<t.toCall);if(!pending.length)return nextStreet(t);t.liveTurn=around(t,after,i=>pending.includes(i));t.turnDeadline=Date.now()+20000}
function start(t){const active=seats(t);if(active.length<2){t.finished=true;t.liveTurn=-1;t.turnDeadline=0;t.nextHandAt=Date.now()+3000;return}t.deck=cards();t.boardCards=[];t.street=0;t.potAmt=0;t.finished=false;t.handNo=(t.handNo||0)+1;t.folded=t.players.map(p=>!p||p.chips<=0);t.liveSeatBets=t.players.map(()=>0);t.contributions=t.players.map(()=>0);t.acted=t.players.map(()=>false);t.holes=t.players.map(p=>p&&p.chips>0?Array.from({length:t.currentTable.type==='omaha'?4:2},()=>take(t)):[]);t.liveDealer=around(t,Number.isInteger(t.liveDealer)?t.liveDealer:active[active.length-1],i=>active.includes(i));t.liveSB=active.length===2?t.liveDealer:around(t,t.liveDealer,i=>active.includes(i));t.liveBB=around(t,t.liveSB,i=>active.includes(i));pay(t,t.liveSB,num(t.currentTable.sb)||100);pay(t,t.liveBB,num(t.currentTable.bb)||200);t.toCall=Math.max(...t.liveSeatBets);t.minRaise=num(t.currentTable.bb)||200;t.liveTurn=around(t,t.liveBB,i=>canAct(t,i));t.turnDeadline=Date.now()+20000;t.statusText='Тоглолт эхэллээ';if(t.liveTurn<0)runout(t)}
function action(t,i,kind,amount){if(!canAct(t,i))return'NO_CHIPS';const need=Math.max(0,t.toCall-t.liveSeatBets[i]);if(kind==='fold')t.folded[i]=true;else if(kind==='check'){if(need)return'CALL_REQUIRED'}else if(kind==='call')pay(t,i,need);else if(kind==='raise'||kind==='allin'){const chips=t.players[i].chips;const proposed=kind==='allin'?chips:Number(amount);if(!Number.isSafeInteger(proposed)||proposed<=0||proposed>chips)return'BAD_BET';const newBet=t.liveSeatBets[i]+proposed;if(proposed<=need)return'RAISE_REQUIRED';const increase=newBet-t.toCall;if(increase<t.minRaise&&proposed!==chips)return'MIN_RAISE';pay(t,i,proposed);if(increase>=t.minRaise){t.minRaise=increase;t.acted=t.acted.map((v,j)=>j===i?v:false)}t.toCall=newBet}else return'BAD_ACTION';t.acted[i]=true;settle(t,i);return null}
function tick(t){let changed=false;const now=Date.now();if(t.finished&&t.nextHandAt&&now>=t.nextHandAt&&seats(t).length>=2){start(t);changed=true}else if(!t.finished&&t.liveTurn>=0&&t.turnDeadline&&now>=t.turnDeadline){const i=t.liveTurn;const need=Math.max(0,t.toCall-t.liveSeatBets[i]);action(t,i,need?'fold':'check');changed=true}else if(!t.finished&&t.liveTurn>=0&&t.players[t.liveTurn]?.botId){const i=t.liveTurn,need=Math.max(0,t.toCall-t.liveSeatBets[i]);action(t,i,need===0?'check':need<=t.players[i].chips/3?'call':'fold');changed=true}if(changed)save(t)}
function view(t,pid){const s=JSON.parse(JSON.stringify(t));delete s.deck;delete s.contributions;delete s.acted;delete s.presence;const viewer=s.players.findIndex(p=>p&&p.playerId===pid);if(!s.finished)s.holes=s.holes.map((h,i)=>i===viewer?h:[]);return s}
app.get('/',(req,res)=>res.json({ok:true,service:'MONGOL_POKER_SERVER'}));app.get('/health',(req,res)=>res.json({ok:true,tables:Object.keys(tables).length}));
app.get('/api/tables/:tableId/state',(req,res)=>{const t=tables[id(req.params.tableId)];if(!t)return error(res,'TABLE_NOT_FOUND',404);tick(t);res.json({ok:true,state:view(t,id(req.query.playerId))})});
app.post('/api/tables/:tableId/join',(req,res)=>{const key=id(req.params.tableId),pid=id(req.body?.playerId);if(!key||!pid)return error(res,'BAD_ID');let t=tables[key],joinedNew=false;if(!t){const meta=req.body.table||{},buy=num(meta.buy);t={tableId:key,currentTable:{...meta,id:key,type:meta.type==='omaha'?'omaha':'texas',sb:num(meta.sb)||100,bb:num(meta.bb)||200,buy},players:[],holes:[],folded:[],revision:0,handNo:0,liveDealer:-1,rakeTotal:0};tables[key]=t;t.players.push({playerId:pid,name:String(req.body.players?.[0]?.name||pid).slice(0,40),chips:buy,emoji:'😎',user:true});for(const b of (Array.isArray(req.body.players)?req.body.players:[]).filter(p=>p.botId).slice(0,5)){const bid='bot_'+id(b.botId);if(!t.players.some(p=>p.playerId===bid))t.players.push({playerId:bid,botId:b.botId,name:String(b.name||'Bot').slice(0,40),chips:num(b.chips)||buy,emoji:b.emoji||'🤖'})}joinedNew=true;start(t)}else if(!t.players.some(p=>p.playerId===pid)){if(t.players.length>=9)return error(res,'TABLE_FULL',409,t,pid);t.players.push({playerId:pid,name:String(req.body.players?.[0]?.name||pid).slice(0,40),chips:num(t.currentTable.buy),emoji:'😎',user:true});joinedNew=true}save(t);res.json({ok:true,joinedNew,state:view(t,pid)})});
app.post('/api/tables/:tableId/action',(req,res)=>{const t=tables[id(req.params.tableId)],pid=id(req.body?.playerId);if(!t)return error(res,'TABLE_NOT_FOUND',404);tick(t);const i=t.players.findIndex(p=>p.playerId===pid);if(i<0)return error(res,'NOT_SEATED',403,t,pid);if(Number(req.body.expectedRevision)!==t.revision)return error(res,'STALE_STATE',409,t,pid);if(t.finished)return error(res,'HAND_FINISHED',409,t,pid);if(i!==t.liveTurn)return error(res,'NOT_YOUR_TURN',409,t,pid);const issue=action(t,i,req.body.action,req.body.amount);if(issue)return error(res,issue,409,t,pid);save(t);res.json({ok:true,state:view(t,pid)})});
app.post('/api/tables/:tableId/presence',(req,res)=>{const t=tables[id(req.params.tableId)];if(!t)return error(res,'TABLE_NOT_FOUND',404);t.presence=t.presence||{};t.presence[id(req.body?.playerId)]={online:!!req.body?.online,at:Date.now()};save(t);res.json({ok:true,state:view(t,id(req.body?.playerId))})});
app.post('/api/tables/:tableId/init',(req,res)=>error(res,'SERVER_AUTHORITATIVE_STATE',403));app.put('/api/tables/:tableId/state',(req,res)=>error(res,'SERVER_AUTHORITATIVE_STATE',403));
setInterval(()=>{for(const t of Object.values(tables))try{tick(t)}catch(e){console.error('Tick error:',e)}},800).unref();
for(const sig of ['SIGTERM','SIGINT'])process.on(sig,()=>process.exit(0));
if(require.main===module)app.listen(PORT,'0.0.0.0',()=>console.log('MONGOL_POKER_SERVER listening '+PORT));
module.exports={app,score5,best,finish,start,action,tables,tick};
